version: '3'

services:
  ticktok:
    image: ${TICKTOK_IMAGE:-ticktok/ticktok:master}
    ports:
      - 9643:9643
    environment:
      - CLOCKS_PURGE_INTERVAL=4000
      - SCHEDULES_PURGE_INTERVAL=1000
      - TICKS_PURGE_INTERVAL=500
      - TICKS_PURGE_KEEPCOUNT=1


